Changing bazel skylib version from 1.1.1 to 1.3.0
bazelbuild/rules_proto pull request #158
Opened 2022-11-14 14:27 UTC by Clement-Jean

This intends to be solving issue #10965 and #2530. It just updates bazel skylib to version 1.3.0.

2022-11-14 15:42 UTC, Yannic commented
Thanks! Could you also update dependencies.bzl please?

2022-11-15 02:03 UTC, Yannic approved these changes

2022-11-15 02:04 UTC, Yannic requested changes

2022-11-15 02:04 UTC, Yannic commented on proto/private/dependencies.bzl
>          "sha256": "c6966ec828da198c5d9adbaa94c05e3a1c7f21bd012a0b29ba8ddbccb2c93b0d",
Actually, you'll need to update this also to get CI green

2022-11-15 15:56 UTC, comius approved these changes

2022-11-15 16:37 UTC, Yannic approved these changes

2022-11-15 17:23 UTC, merged