Upgrade protobuf to 3.17.0
bazelbuild/rules_proto pull request #88
Opened 2021-05-20 00:04 UTC by tandel-pratik

2021-05-24 22:40 UTC, tandel-pratik commented
hey @comius @lberki is it possible to merge this? these proto upgrade contains some new kotlin generated bindings that we'd find really useful

2021-05-28 10:40 UTC, Yannic approved these changes
LGTM

@meteorcloudy Can you please help with uploading the following files?
`https://github.com/protocolbuffers/protobuf/archive/v3.17.0.tar.gz`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-linux-aarch_64.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-linux-ppcle_64.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-linux-s390_64.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-linux-x86_32.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-linux-x86_64.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-osx-x86_64.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-win32.zip`
`https://github.com/protocolbuffers/protobuf/releases/download/v3.17.0/protoc-3.17.0-win64.zip`
`https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.17.0/protobuf-java-3.17.0.jar`
`https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.17.0/protobuf-java-3.17.0-sources.jar`
`https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.17.0/protobuf-java-util-3.17.0.jar`
`https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.17.0/protobuf-java-util-3.17.0-sources.jar`
`https://repo1.maven.org/maven2/com/google/protobuf/protobuf-javalite/3.17.0/protobuf-javalite-3.17.0.jar`
`https://repo1.maven.org/maven2/com/google/protobuf/protobuf-javalite/3.17.0/protobuf-javalite-3.17.0-sources.jar`

2021-05-31 08:34 UTC, meteorcloudy commented
@Yannic The artifacts should be available through Bazel mirror.

2021-06-07 17:03 UTC, tandel-pratik commented
hey @Yannic @meteorcloudy can this be merged now that the artifacts are available?

2021-06-17 09:05 UTC, comius requested changes

2021-06-17 09:05 UTC, comius commented on proto/private/dependencies.bzl
> +    "com_google_protobuf_protoc_linux_s390_64": {
Please fix reference to com_google_protobuf_protoc_linux_s390 in proto/private/BUILD.release.

2021-06-17 16:02 UTC, comius approved these changes

2021-06-17 16:09 UTC, merged

2021-08-02 16:57 UTC, kconvey commented
@meteorcloudy What is the URL for the bazel mirror? Can we update `README.md` to reflect supporting 3.17.0? 

Happy to do it if I have the new URL.

2021-08-03 09:00 UTC, meteorcloudy commented
See https://github.com/bazelbuild/rules_proto/pull/88/files#diff-374db506507a0693f52d91212c45c56983f9d38960cd9ad732fcf774b68d201bR29

What README.md do you mean?